package pt.ipg.mcm.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pt.ipg.mcm.entities.Produto;

import pt.ipg.mcm.entities.ProdutoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig produtoDaoConfig;

    private final ProdutoDao produtoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        produtoDaoConfig = daoConfigMap.get(ProdutoDao.class).clone();
        produtoDaoConfig.initIdentityScope(type);

        produtoDao = new ProdutoDao(produtoDaoConfig, this);

        registerDao(Produto.class, produtoDao);
    }
    
    public void clear() {
        produtoDaoConfig.getIdentityScope().clear();
    }

    public ProdutoDao getProdutoDao() {
        return produtoDao;
    }

}
